# This is a basic workflow to help you get started with Actions

name: sdk-workflow

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: set GOMODULES
        run: export GO111MODULE=on
      # Runs a set of commands using the runners shell
      - name: install gcc
        run: |
          sudo apt update
          sudo apt install build-essential
          sudo apt-get install manpages-dev
          gcc --version
      - name: Install operator-sdk
        run: |
          RELEASE_VERSION=v1.2.0
          curl -LO https://github.com/operator-framework/operator-sdk/releases/download/${RELEASE_VERSION}/operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
          chmod +x operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu && sudo mkdir -p /usr/local/bin/ && sudo cp operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu /usr/local/bin/operator-sdk && rm operator-sdk-${RELEASE_VERSION}-x86_64-linux-gnu
      - name: Check version
        run: |
          operator-sdk version
      - name: quickstart install
        run: |
          mkdir memcached-operator
          cd memcached-operator
          operator-sdk init --domain=example.com --repo=github.com/example-inc/memcached-operator
      - name: create api
        run: |
          operator-sdk create api --group=cache --version=v1alpha1 --kind=Memcached --resource=true --controller=true
